---
ansible_host: 172.31.5.6
wg_packages: 
  - wireguard
  - nftables
wg_name: wg0
wg_ifname: enp1s0
wg_address: 192.168.100.1
wg_address_netmask: 24
wg_listen_port: 52820
wg_peers:
  192.168.100.2:
    wg_peer_comment: "work laptop"
    wg_peer_publickey: ""
      #wg_peer_allowedips: "172.31.10.10/32, 172.31.2.2/32, 172.31.2.4/32, 172.31.2.15/32"
    wg_peer_allowedips: "0.0.0.0/0"
  192.168.100.3:
    wg_peer_comment: "another laptop"
    wg_peer_publickey: ""
    wg_peer_allowedips: "0.0.0.0/0"


