---
- import_playbook: network.yaml
- import_playbook: users.yaml
- import_playbook: sshd.yaml
- import_playbook: packages.yaml
- import_playbook: zfs.yaml
- import_playbook: ntp.yaml
- import_playbook: git-home.yaml
- import_playbook: docker.yaml
- import_playbook: kvm.yaml
- import_playbook: samba.yaml
- import_playbook: ups-nut.yaml
- import_playbook: sudo.yaml
- import_playbook: services.yaml
- import_playbook: sanoid.yaml
