---
# Encrypt me
users:
  bobbytables:
    password: changeme
    groups: sudo,zfsadmin
    shell: /usr/bin/bash
  ansible:
    password: changeme
    groups: sudo,zfsadmin
    public_key: |
      ssh-rsa AAAAB3N... bobbytables@some.host

    git_ssh_private_key_name: gitinternal

    git_ssh_private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      private_git_ssh_key
      -----END OPENSSH PRIVATE KEY-----

    github_ssh_private_key_name: github

    github_ssh_private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      github_ssh_key
      -----END OPENSSH PRIVATE KEY-----


  git:
    password: changeme
    groups: git
    shell: /usr/bin/bash
sambausers:
  bobbytables:
    password: changeme

nutzeuspassword: changeme
nutnyxpassword: changeme
plex_claim: whyareyoustillrunningplex
service_secrets:
  adguard:
    user: bobbytables
    password: changeme
  frigate:
    rtsp_password: "password"
    cam_user: "bobbytables"
    cam_password: "changeme"
  gitea:
    postgresqluser: "gitea"
    postgresqlpassword: "changeme"
  gluetun:
    vpn_endpoint_ip: "4.3.2.1"
    vpn_endpoint_port: "51820"
    vpn_endpoint_public_key: "public="
    vpn_endpoint_private_key: "private="
  gnucash_mysql:
    dbuser: "gnucash"
    dbpassword: "changeme"
    dbname: "gnucash"
  gnucash_postgres:
    dbuser: "gnucash"
    dbpassword: "changeme"
    dbname: "gnucash"
