---
vmname: "zeus-dev"
dev_kvm_pool: "/data/kvm-nvme2"
hostname: "zeus-dev"
domain: "lab.internal"
os_disk: "/dev/vda"
podman_preseed_ip: 172.31.8.2
mainnetwork:
  iface: enp1s0
  mvname: prod1
  netmask: 255.255.255.0
  address: 172.31.8.60
  gateway: 172.31.8.1
  dns1: 1.1.1.1
  dns2: 4.4.4.4
  mv_subnet: "172.31.8.0/24"
  mv_gateway: "172.31.8.1"
  mv_iprange: "172.31.8.96/27"

mvnetworks: 
  mvlanprod2:
    iface: enp2s0
    ifacemv: mvlanprod2
    iproute: "192.168.22.0/24"
    iproutesrc: 192.168.22.2
    iproutetable: prod
    iproutenum: 240
    iprule: "192.168.22.2/32"
    address: "192.168.22.2"
    gateway: 192.168.22.1
    dns1: 1.1.1.1
    dns2: 4.4.4.4
    dnssearch: lab.internal
    docker_subnet: "192.168.22.0/24"
    docker_gateway: "192.168.22.1"
    docker_iprange: "192.168.22.0/24"
  mvlandev3:
    iface: enp3s0
    ifacemv: mvlandev3
    iproute: "192.168.23.0/24"
    iproutesrc: 192.168.23.2
    iproutetable: dev
    iproutenum: 241
    iprule: "192.168.23.2/32"
    address: "192.168.23.2"
    gateway: 192.168.23.1
    dns1: 1.1.1.1
    dns2: 4.4.4.4
    dnssearch: lab.internal
    docker_subnet: "192.168.23.0/24"
    docker_gateway: "192.168.23.1"
    docker_iprange: "192.168.23.0/24"
brnetworks:
  vm4:
    iface: enp4s0
    ifacev: vm4
    iproute: "192.168.24.0/24"
    iproutesrc: 192.168.24.2
    iproutetable: vm
    iproutenum: 242
    iprule: "192.168.24.2/32"
    address: 192.168.24.2
    gateway: 192.168.24.1
    network: 192.168.24.0
    broadcast: 192.168.24.255
    dns1: 1.1.1.1
    dns2: 4.4.4.4
    dnssearch: lab.internal
disks:
  zeus-dev:
    size: 100G
  zfs1: 
    size: 50G
  zfs2: 
    size: 50G
  zfs3: 
    size: 50G
  zfs4: 
    size: 50G
  zfs5: 
    size: 50G
  zfs6: 
    size: 50G
ansible_user: ansible
packages:
  - lm-sensors
  - linux-headers-amd64
  - qemu-system
  - libvirt-daemon-system
  - libguestfs-tools
  - virtinst
  - libosinfo-bin
  - bridge-utils
  - rsync
  - tmux
  - vim
  - bash-completion
  - python3
  - man-db
  - sanoid
  # Needed for docker, adding repo
  - apt-transport-https
  - ca-certificates
  - wget
  - software-properties-common
  - gnupg2
  - curl
  - python3-docker
  - python3-libvirt
  - python3-lxml
zpool_name: data
zpool_mode: raidz2
zpool_options: 
  - ashift=12
zpool_disks: 
  - /dev/vdb
  - /dev/vdc
  - /dev/vdd
  - /dev/vde
  - /dev/vdf
  - /dev/vdg
zpool_cache: /dev/vdh
zfs_create_pool: true
zfs_create_datasets: true
zfs_datasets:
  Backup:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
    options: 
      - compression=zstd
      - atime=off
      - exec=off
  BackupCritical:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
    options: 
      - compression=zstd
  Books:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
    options: 
      - compression=zstd
  Documentaries:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
  Downloads:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
    options: 
      - compression=zstd
  Git:
    user: git
    group: git
    mode: '0755'
    options: 
      - compression=zstd
  homebackup:
    user: bobbytables
    group: bobbytables
    mode: '0755'
    options: 
      - compression=zstd
  Misc:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
    options: 
      - compression=zstd
  Movies:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
  MoviesArchive:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
  MoviesBad:
    user: bobbytables
    group: bobbytables
    mode: '0700'
  Music:
    user: bobbytables
    group: zfsadmin
    mode: '0755'
  Pictures:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
  Software:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
  SWEG:
    user: bobbytables
    group: bobbytables
    mode: '0775'
  TVShows:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
  Video:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
  Workouts:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
  WorkoutsPlex:
    user: bobbytables
    group: zfsadmin
    mode: '0775'
kvm_pools: 
  kvm_pool: 
    directory: "/kvm_pool"
zeusgroups:
  - zfsadmin
  - backupadmin
  - git
dockerusers: 
  - ansible
  - bobbytables
kvmusers: 
  - ansible
  - bobbytables
sudo_nopasswd:
  bobbytables:
    commands:
      - "/usr/sbin/zfs send *"
      - "/usr/sbin/zfs recv *"
  ansible:
    commands:
      - "/usr/sbin/zfs send *"
      - "/usr/sbin/zfs recv *"
      - "/usr/bin/apt update *"
      - "/usr/bin/apt -y update *"
      - "/usr/bin/apt -y upgrade *"
