---
# tasks file for users
- name: Add groups
  become: True
  ansible.builtin.group: 
    name: "{{ item }}"
    state: present
  loop: "{{ zeusgroups }}"
- name: Add users
  become: True
  ansible.builtin.user: 
    name: "{{ item.key }}"
    password: "{{ item.value.password | password_hash('sha512') }}"
    groups: "{{ item.value.groups }}"
    home: "{{ item.value.home | default(omit) }}"
    shell: "{{ item.value.shell | default(omit) }}"
    append: yes
  loop: "{{ users | dict2items }}"
