mqtt:
  enabled: false
cameras:
  armcrest_4mp_prohd: # <------ Name the camera
    enabled: true
    onvif:
      host: 172.31.51.51
      port: 80
      user: admin
      password: changeme
    ffmpeg:
      inputs:
        #- path: rtsp://admin:changeme@172.31.51.51:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for detection
        - path: rtsp://admin:changeme@172.31.51.51:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection subtype 1 is low res
          roles:
            - detect
        - path: rtsp://admin:changeme@172.31.51.51:554/cam/realmonitor?channel=1&subtype=0 # <----- The stream you want to use for recording
          roles:
            - record
            - audio
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      fps: 5
    motion:
      threshold: 16
      contour_area: 9
      improve_contrast: 'false'
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 30
      mode: motion
detectors:
  zeustensorrt:
    type: tensorrt
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
ffmpeg:
  hwaccel_args: preset-nvidia-h264
objects:
  track:
    - person
    - dog

version: 0.14
